server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/projectats
    username: root
    password: myroot
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect